name: PlayerLimit
main: net.azisaba.playerLimit.PlayerLimit
version: 1.1.0
api-version: 1.13
commands:
  playerlimit:
    permission: playerlimit.command
permissions:
  playerlimit.bypass:
    default: op
